import React from 'react'
import { svgIcon } from '../../../utils/StaticData'
import '../hamMenu/howtoplay.css'
import { FaSackDollar } from "react-icons/fa6";

const GameBoard = ({ setGameBoard, GameBoard }) => {
  return (
    <div className='overlay'>
      <div className='modal modal-2'>
        <div className="modal-header">
          <div className="cross-icon-container-1">
            <div className='info-icon'>

              <div className="" style={{ cursor: "pointer" }} onClick={() => setGameBoard(false)}>
                {svgIcon.backIcon}
              </div>
              <p>Game Board</p>
            </div>
            <div className="cross-icon1" onClick={() => setGameBoard(false)}>
              {svgIcon.closeIconwhite}
            </div>
          </div>

        </div>
        <div className="modal-content1">
          <p className='howtoplay-para'>The game board consists of a line graph that represents how the Multiplier rises over the course of the round.&nbsp;</p> <br />

          <div className="howtoplay-img-container">
            <img src={svgIcon.gameBoardPic} alt="" />
          </div> <br /> <br />

          <p className='gameboard-para'>1. Crash Multiplier</p> <br />
          <p className='howtoplay-para'>The maximum number for the Multiplier is <span>999.99x</span> </p> <br />
          <p className='howtoplay-para'>The Multiplier starts at 1.01x and gradually increases by <span>0.01x</span>  over time. </p> <br /> <br />
          <p className='howtoplay-para'>The Multiplier can crash at 0x approximately every 30 to 50 rounds or even longer due to the game's algorithm. This is considered a website win, thus all players lose in this situation</p> <br /> <br />
          <p className='howtoplay-para'>The color of the crash point will turn red if it is 1.8 and under, green if it is above 1.8.</p> <br /> <br />
          <p className='howtoplay-para'>In classic mode, the Multiplier is used as the Winning Multiplier to calculate the player’s bet winnings.</p> <br /> <br />

          <p className='gameboard-para'>2. Crash Point History</p> <br />
          <div className='gameboard-round'>
            <img src={svgIcon.round} alt='' />
          </div> <br />
          <p className='howtoplay-para'>A list of the Multiplier’s past crash points. Clicking the chip will display information related to the crash point, such as round number, date, time as well as Hash and MD5 numbers. </p> <br /> <br />


          <p className='gameboard-para'>3. Last Result and History</p>
          <div className='gameboard-imoon'>
            <img src={svgIcon.imoon} alt='' />
          </div> <br />
          <p className='howtoplay-para'>In this section of the game, there is a list of past bets placed by players along with all the information related to that round. Additionally, you can view the last hundred rounds played.</p> <br /> <br />

          <p className='gameboard-para'>4. Status Badge </p>
          <div className='gameboard-round-inr'>
            {/* <img src={svgIcon.badge} alt='' /> */}

            <button type='button'>Placed 15,000</button>
          </div> <br />
          <p className='howtoplay-para'>Displays the current state of any placed bets.</p> <br /> <br />

          <p className='gameboard-para'>5. Menu </p>
          <div className='gameboard-imoon'>
            <img src={svgIcon.menu1} alt='' />
          </div> <br />
          <p className='howtoplay-para'>Players can toggle to open/close the menu with this button.</p> <br /> <br /> <br />
          <h2 className='howtoplay-h2'>Mute</h2>
          <div className='gameboard-imoon'>
            <img src={svgIcon.mute} alt='' />
          </div>
          <p className='howtoplay-para'>Players can toggle to mute/unmute the audio with this button.</p> <br />
          <div className='gameboard-imoon'>
            <img src={svgIcon.fair} alt='' />
          </div>
          <h2 className='howtoplay-h2'>Fairness</h2> <br /> <br />

          <p className='howtoplay-para'> Each round begins with the creation of a random crash point generated by an algorithm. This algorithm, a pure function, uses a unique SHA-256 hash to produce a crash point, ensuring the same crash point for identical hashes. For security, the specific hash used is not disclosed. Instead, we reveal the hash's MD5 checksum before the round commences as proof that the hash remains unchanged and unmanipulated during play.Players can find the MD5 checksum from the MD5 chip in the crash point history.</p> <br /> <br />
          <p className="howtoplay-para">Once a round concludes and the game crashes, the original hash is disclosed.&nbsp;Players can check both the MD5 and hash by clicking the crash point history chips or from their bet history. This allows players to verify the authenticity of the crash point by checking the MD5 checksum of the revealed hash against what was initially provided.</p> <br /> <br />
          <p className="howtoplay-para">To facilitate transparency and fairness, we offer an in-game tool named "Fairness." This tool interfaces directly with the algorithm's pure function, enabling players to input the hash and retrieve the corresponding crash point for verification. The process involves two key steps: revealing the hash's MD5 before the round starts and disclosing the actual hash post-crash.</p> <br />

          <div className="howtoplay-img-container3">
            <img src={svgIcon.hash} alt="" />
          </div> <br />

          <div className='gameboard-imoon'>
            <img src={svgIcon.info} alt='' />
          </div>
          <h2 className='howtoplay-h2'>Information</h2> <br /> <br />
          <p className='howtoplay-para'>Players can toggle to open the information with this button</p> <br /> <br />

          <p className='gameboard-para'>6. Active Players  </p>
          <div className='gameboard-round-icon'>
            <img src={svgIcon.player} alt='' />
          </div>
          <p className='howtoplay-para'>Shows the total number of active players.</p> <br /> <br />

          <p className='gameboard-para'>7. Total Bets </p>
          <div className='gameboard-round-dollar'>
            {/* <img src={svgIcon.labels} alt='' /> */}
            <p style={{ color: "white" }}><FaSackDollar /> <span style={{ color: "green" }}>15,000</span></p>
          </div> <br />

          <p className="howtoplay-para">Shows the total bet amount placed by the player.</p> <br />
        </div>
      </div>
    </div>
  )
}

export default GameBoard